import Head from 'next/head';
import { Inter } from '@next/font/google';
import CircleSvg from '../public/images/circle-accent-1.svg';
import Header from '../src/parts/Header';
import Hero from '../src/parts/Hero';
import Clients from '../src/parts/Clients';
import ListCourses from '../src/parts/ListCourses';
import ListCategories from '../src/parts/ListCategories';
import Footer from '../src/parts/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>BWAMICRO</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                <section className="header-clipping pt-10">
                    <CircleSvg className="absolute bottom-0 left-0" />
                    <div className="sunshine"></div>
                    <div className="container mx-auto">
                        <Header onLight={false} />
                        <Hero />
                    </div>
                </section>
                <section className="container mx-auto pt-24">
                    <Clients />
                </section>
                <section className="container mx-auto pt-24">
                    <ListCourses />
                </section>
                <section className="container mx-auto pt-24">
                    <ListCategories />
                </section>
                <section className="bg-indigo-1000 mt-24 py-12">
                    <Footer />
                </section>
            </main>
        </>
    );
}
